version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["npm", "start"]
