import TabHeader from "./tab_header";
import TablePartidas from "../../src/components/table_partidas";
import PartidasRecentes, { Partida } from "../../src/components/partidas_recentes";

// Mockado
//const partidas = [
//	{
//		id: 1,
//		equipe: "Brasil",
//		sigla_equipe: "BRA",
//		adversario: "Espanha",
//		sigla_adversario: "ESP",
//		n_sets: 5,
//		resultado: "3x2",
//		data: "2030-01-16",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 2,
//		equipe: "Brasil",
//		sigla_equipe: "BRA",
//		adversario: "Inglaterra",
//		sigla_adversario: "ENG",
//		n_sets: 3,
//		resultado: "2x3",
//		data: "2029-02-10",
//		situacao: "Derrota",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 3,
//		equipe: "Brasil",
//		sigla_equipe: "BRA",
//		adversario: "Flamengo",
//		sigla_adversario: "FLA",
//		n_sets: 4,
//		resultado: "3x1",
//		data: "2028-03-05",
//		situacao: "Vitória",
//		jogadores_analisados: 7,
//	},
//	{
//		id: 4,
//		equipe: "Japão",
//		sigla_equipe: "JPN",
//		adversario: "Rússia",
//		sigla_adversario: "RUS",
//		n_sets: 5,
//		resultado: "2x3",
//		data: "2025-04-12",
//		situacao: "Derrota",
//		jogadores_analisados: 8,
//	},
//	{
//		id: 5,
//		equipe: "Canadá",
//		sigla_equipe: "CAN",
//		adversario: "Alemanha",
//		sigla_adversario: "GER",
//		n_sets: 3,
//		resultado: "3x1",
//		data: "2025-05-20",
//		situacao: "Vitória",
//		jogadores_analisados: 4,
//	},
//	{
//		id: 6,
//		equipe: "Sérvia",
//		sigla_equipe: "SRB",
//		adversario: "Polônia",
//		sigla_adversario: "POL",
//		n_sets: 4,
//		resultado: "3x1",
//		data: "2025-06-15",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 7,
//		equipe: "China",
//		sigla_equipe: "CHN",
//		adversario: "Coreia do Sul",
//		sigla_adversario: "KOR",
//		n_sets: 3,
//		resultado: "0x3",
//		data: "2025-07-22",
//		situacao: "Derrota",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 8,
//		equipe: "Austrália",
//		sigla_equipe: "AUS",
//		adversario: "Holanda",
//		sigla_adversario: "NED",
//		n_sets: 5,
//		resultado: "3x2",
//		data: "2025-08-30",
//		situacao: "Vitória",
//		jogadores_analisados: 7,
//	},
//	{
//		id: 9,
//		equipe: "Bélgica",
//		sigla_equipe: "BEL",
//		adversario: "Turquia",
//		sigla_adversario: "TUR",
//		n_sets: 3,
//		resultado: "3x0",
//		data: "2025-09-10",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 10,
//		equipe: "Irã",
//		sigla_equipe: "IRN",
//		adversario: "Egito",
//		sigla_adversario: "EGY",
//		n_sets: 4,
//		resultado: "3x1",
//		data: "2025-10-05",
//		situacao: "Vitória",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 11,
//		equipe: "Cuba",
//		sigla_equipe: "CUB",
//		adversario: "Porto Rico",
//		sigla_adversario: "PRI",
//		n_sets: 3,
//		resultado: "2x3",
//		data: "2025-11-12",
//		situacao: "Derrota",
//		jogadores_analisados: 4,
//	},
//	{
//		id: 12,
//		equipe: "Bulgária",
//		sigla_equipe: "BUL",
//		adversario: "República Tcheca",
//		sigla_adversario: "CZE",
//		n_sets: 5,
//		resultado: "3x2",
//		data: "2025-12-18",
//		situacao: "Vitória",
//		jogadores_analisados: 8,
//	},
//	{
//		id: 13,
//		equipe: "Chile",
//		sigla_equipe: "CHI",
//		adversario: "Venezuela",
//		sigla_adversario: "VEN",
//		n_sets: 3,
//		resultado: "3x0",
//		data: "2026-01-05",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 14,
//		equipe: "Peru",
//		sigla_equipe: "PER",
//		adversario: "Colômbia",
//		sigla_adversario: "COL",
//		n_sets: 4,
//		resultado: "1x3",
//		data: "2026-02-14",
//		situacao: "Derrota",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 15,
//		equipe: "México",
//		sigla_equipe: "MEX",
//		adversario: "Costa Rica",
//		sigla_adversario: "CRI",
//		n_sets: 3,
//		resultado: "3x1",
//		data: "2026-03-20",
//		situacao: "Vitória",
//		jogadores_analisados: 7,
//	},
//	{
//		id: 16,
//		equipe: "Uruguai",
//		sigla_equipe: "URU",
//		adversario: "Paraguai",
//		sigla_adversario: "PAR",
//		n_sets: 5,
//		resultado: "2x3",
//		data: "2026-04-25",
//		situacao: "Derrota",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 17,
//		equipe: "Equador",
//		sigla_equipe: "ECU",
//		adversario: "Bolívia",
//		sigla_adversario: "BOL",
//		n_sets: 3,
//		resultado: "3x0",
//		data: "2026-05-30",
//		situacao: "Vitória",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 18,
//		equipe: "Portugal",
//		sigla_equipe: "POR",
//		adversario: "Espanha",
//		sigla_adversario: "ESP",
//		n_sets: 4,
//		resultado: "3x1",
//		data: "2026-06-10",
//		situacao: "Vitória",
//		jogadores_analisados: 8,
//	},
//	{
//		id: 19,
//		equipe: "Suíça",
//		sigla_equipe: "SUI",
//		adversario: "Áustria",
//		sigla_adversario: "AUT",
//		n_sets: 3,
//		resultado: "0x3",
//		data: "2026-07-15",
//		situacao: "Derrota",
//		jogadores_analisados: 4,
//	},
//	{
//		id: 20,
//		equipe: "Suécia",
//		sigla_equipe: "SWE",
//		adversario: "Noruega",
//		sigla_adversario: "NOR",
//		n_sets: 5,
//		resultado: "3x2",
//		data: "2026-08-20",
//		situacao: "Vitória",
//		jogadores_analisados: 7,
//	},
//	{
//		id: 21,
//		equipe: "Dinamarca",
//		sigla_equipe: "DEN",
//		adversario: "Finlândia",
//		sigla_adversario: "FIN",
//		n_sets: 3,
//		resultado: "3x1",
//		data: "2026-09-25",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 22,
//		equipe: "Grécia",
//		sigla_equipe: "GRE",
//		adversario: "Croácia",
//		sigla_adversario: "CRO",
//		n_sets: 4,
//		resultado: "2x3",
//		data: "2026-10-30",
//		situacao: "Derrota",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 23,
//		equipe: "Romênia",
//		sigla_equipe: "ROU",
//		adversario: "Hungria",
//		sigla_adversario: "HUN",
//		n_sets: 3,
//		resultado: "3x0",
//		data: "2026-11-05",
//		situacao: "Vitória",
//		jogadores_analisados: 4,
//	},
//	{
//		id: 24,
//		equipe: "Ucrânia",
//		sigla_equipe: "UKR",
//		adversario: "Bielorrússia",
//		sigla_adversario: "BLR",
//		n_sets: 5,
//		resultado: "3x2",
//		data: "2026-12-10",
//		situacao: "Vitória",
//		jogadores_analisados: 8,
//	},
//	{
//		id: 25,
//		equipe: "Israel",
//		sigla_equipe: "ISR",
//		adversario: "Líbano",
//		sigla_adversario: "LBN",
//		n_sets: 3,
//		resultado: "3x1",
//		data: "2027-01-15",
//		situacao: "Vitória",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 26,
//		equipe: "África do Sul",
//		sigla_equipe: "ZAF",
//		adversario: "Nigéria",
//		sigla_adversario: "NGA",
//		n_sets: 4,
//		resultado: "1x3",
//		data: "2027-02-20",
//		situacao: "Derrota",
//		jogadores_analisados: 5,
//	},
//	{
//		id: 27,
//		equipe: "Quênia",
//		sigla_equipe: "KEN",
//		adversario: "Egito",
//		sigla_adversario: "EGY",
//		n_sets: 3,
//		resultado: "3x0",
//		data: "2027-03-25",
//		situacao: "Vitória",
//		jogadores_analisados: 7,
//	},
//	{
//		id: 28,
//		equipe: "Marrocos",
//		sigla_equipe: "MAR",
//		adversario: "Tunísia",
//		sigla_adversario: "TUN",
//		n_sets: 5,
//		resultado: "2x3",
//		data: "2027-04-30",
//		situacao: "Derrota",
//		jogadores_analisados: 6,
//	},
//	{
//		id: 29,
//		equipe: "Argélia",
//		sigla_equipe: "DZA",
//		adversario: "Senegal",
//		sigla_adversario: "SEN",
//		n_sets: 3,
//		resultado: "3x1",
//		data: "2027-05-05",
//		situacao: "Vitória",
//		jogadores_analisados: 5,
//	},
//];


interface AbaPartidasProps {
	matches: Partida[];
}

function AbaPartidas({matches}: AbaPartidasProps) {
	const partidasOrdenadas = matches.sort((a, b) => {
		// Converte as datas para objetos Date e compara
		return new Date(b.data).getTime() - new Date(a.data).getTime();
	});
	
	// Seleciona as três partidas mais recentes
	const tresPartidasRecentes = partidasOrdenadas.slice(0, 3);
	return (
		<div className="flex flex-col gap-10">
			<TabHeader
				texto="Total de partidas analisadas nesta equipe"
				numero={matches.length}
				botao="+ Adicionar partida"
				route="/nova-partida"
			/>
			<PartidasRecentes
				item1={tresPartidasRecentes[0]}
				item2={tresPartidasRecentes[1]}
				item3={tresPartidasRecentes[2]}
			/>
			<TablePartidas items={matches} title="Todas as partidas" />
		</div>
	);
}

export default AbaPartidas;
